// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiC9lZ2h8plQQiJ9_TdCMcaXs4TmkgL-c',
    appId: '1:513230387484:web:99053b3d6c98ca6228a2d9',
    messagingSenderId: '513230387484',
    projectId: 'nerdy-health',
    authDomain: 'nerdy-health.firebaseapp.com',
    storageBucket: 'nerdy-health.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBRQ1x044DxgZp0cO4mo4nGMfA7b7YOpM',
    appId: '1:513230387484:android:bfe9d442f7e942dd28a2d9',
    messagingSenderId: '513230387484',
    projectId: 'nerdy-health',
    storageBucket: 'nerdy-health.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5HHu7gqXO-RYce8FRVWQ6FbvsypqjLIw',
    appId: '1:513230387484:ios:b480a50a8a23da5e28a2d9',
    messagingSenderId: '513230387484',
    projectId: 'nerdy-health',
    storageBucket: 'nerdy-health.firebasestorage.app',
    iosBundleId: 'com.example.nerdyHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5HHu7gqXO-RYce8FRVWQ6FbvsypqjLIw',
    appId: '1:513230387484:ios:b480a50a8a23da5e28a2d9',
    messagingSenderId: '513230387484',
    projectId: 'nerdy-health',
    storageBucket: 'nerdy-health.firebasestorage.app',
    iosBundleId: 'com.example.nerdyHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiC9lZ2h8plQQiJ9_TdCMcaXs4TmkgL-c',
    appId: '1:513230387484:web:84fa469e26d6ed6328a2d9',
    messagingSenderId: '513230387484',
    projectId: 'nerdy-health',
    authDomain: 'nerdy-health.firebaseapp.com',
    storageBucket: 'nerdy-health.firebasestorage.app',
  );
}
